### ISSUE TITLE
New collaborators

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr-python-client#102]
Continues the tradition of #55. (@waldyrious if you think any of the previous names should still be on the list, just add them here)

An organization member should invite the following people to be repository collaborattors, as they qualify for the repository collaborator status:
- [x] @MasterOdin

**Comment by sbrl** [comment]
Hey, that do you say, @MasterOdin? Would you like an invite to be a repo collaborator for the tldr-python-client?

**Comment by MasterOdin** [comment]
Sure

**Comment by zdroid** [comment]
ping @sbrl

**Comment by sbrl** [comment]
Invite sent, @MasterOdin!

Just for future reference,I've sent an invite for write access. The permissions system has been upgraded though, so there are now 2 additional roles above write:

 - _Maintain_
 - _Admin_

**Comment by MasterOdin** [comment]
accepted, thanks @sbrl and @zdroid
