### ISSUE TITLE
tldr "documentation is not available"

### ISSUE THREAD

**Issue by maksmeshkov** [tldr-pages/tldr-python-client#119]
`tldr {command} `
outputs
` "{command}" documentation is not available. Consider contributing Pull Request to https://github.com/tldr-pages/tldr `
given any command.
ping github.com works, tldr -u outputs "Updated cache for 0 entries"

**Comment by zdroid** [comment]
Are you using the latest version? This should have been fixed in #112.

**Comment by MasterOdin** [comment]
What is the value of your `LANG`and `LANGUAGES`environment variables?

**Comment by maksmeshkov** [comment]
> What is the value of your `LANG`and `LANGUAGES`environment variables?

`LANG=cv_RU.UTF-8`

running `export LANG="en_US.utf8"` solved the issue
