### ISSUE TITLE
Create GH action release workflow

### ISSUE THREAD

**Issue by MasterOdin** [tldr-pages/tldr-python-client#128]
A note to myself, it would be good to create a GH release workflow such that on tagged releases through the GH interface, it would then handle the aspect of pushing the new version to pypi.

**Comment by samuel-w** [comment]
I found this that can be used https://github.com/pypa/gh-action-pypi-publish

**Comment by MasterOdin** [comment]
Done in 45f9f263384bdca1cc4a072f1447354091112001
