### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by bmccorm2** [tldr-pages/tldr-python-client#137]
I have a fresh arch install and get this error message after i install the program and all its dependencies:

![image](https://user-images.githubusercontent.com/11781610/92279322-45281480-eeb4-11ea-93e0-a456ff6a0b50.png)

**Comment by bmccorm2** [comment]
Ah ok  that makes sense.  In that case it was my fault and i probably missed a configuration step in my system.  I went back through all the lang settings and now it is working fine.  Thanks!

**Comment by danlkv** [comment]
@bmccorm2 I think it is still a bug in tldr, it shouldn't crash with a cryptic message, but either print an error about the `lang` variable or, better, fallback to english.
