### ISSUE TITLE
Show english page when no page is found for the current locale

### ISSUE THREAD

**Issue by Roboron3042** [tldr-pages/tldr-python-client#138]
It's so confusing to search for a tldr and get not results for commands you know it's sure they have one. Until you notice it's only showing you results on your current locale...

I suggest tldr to show the english page when no page is found for your current locale. It is a saner default, and it is was man does, for example.

**Comment by sbrl** [comment]
Hey there, @Roboron3042! You mentioned that you're using the tldr python client.

tldr-pages/tldr is only for the tldr pages themselves, rather than the clients. I've transferred your issue over to the tldr-pages/tldr-python-client repo :-)

/cc @MasterOdin, and maybe @zdroid

**Comment by MasterOdin** [comment]
Yup, with tldr-pages/tldr#4246 merged which makes this behavior part of the specification, this will be part of the next python release, which I hope to cut in the next week or so.

This behavior though was implemented in #123, and is available on master.
