### ISSUE TITLE
TLDR should be caching the pages

### ISSUE THREAD

**Issue by d33tah** [tldr-pages/tldr-python-client#15]
I waited way too long for my `tldr nmap` page to display. TLDR should IMHO be caching the pages it uses - perhaps all of them.

**Comment by felixonmars** [comment]
Now I am waiting for the reference client, and will update python client according to it :)

**Comment by bwh1te** [comment]
Where should we store cache? Guys do you know best practices about caching results in same cases?

**Comment by JacobCallahan** [comment]
I'm seeing pretty quick response times.

```
$ time tldr nmap
...
real	0m0.700s
user	0m0.085s
sys	0m0.013s
```
with that said, the cache could be stored in either the install directory, (/usr/bin/tldr for me) or as a new dotfolder in the user's home directory.

**Comment by felixonmars** [comment]
This has been implemented in newer versions.
