### ISSUE TITLE
tldr always get data from url without using cache if the platform is empty.

### ISSUE THREAD

**Issue by ramwin** [tldr-pages/tldr-python-client#150]
My system: ubuntu 20.04
My tldr version: latest. 

In the code:

https://github.com/tldr-pages/tldr-python-client/blob/daf1ebf8e9c54376b2d22873e3b8dcf854cb48b9/tldr.py#L194-L204

the tldr client will always try to find the command in linux platform first. So if a command is common (like, `ls`, `zip`), the `tldr` command will first try to find cache file only in `<cache_dir>/linux/ls.md` and since the `ls.md` is in the `<cache_dir>/common/ls.md`, not in the `<cache_dir>/linux/ls.md`, the cache failed.  

Then, the client will try to get `<remote_url>/linux/ls.md` from remote server. and the remote server return 404.  

After that, the client will use the platform `common` and the cache is found.  

I suggest change code like this:

    for platform in platforms:  # find cache first
        try:
            load_page_from_cache(command, platform, languate)
        except Exception:
            continue
    for platform in platforms:  # if failed , get it from server
        try:
            load_page_from_server(command, platform, languate)
        except Exception:
            continue

**Comment by ramwin** [comment]
I created a [pr](https://github.com/tldr-pages/tldr-python-client/pull/151) to fix it.

**Comment by ZJUGuoShuai** [comment]
Yes, I just encountered the same issue.

In my area I couldn't connect to the URL directly without using an proxy. Consequently, the command `tldr find` won't work - it doesn't use the cache, the output is:
```
Error fetching from tldr: <urlopen error [Errno 111] Connection refused>
```

But when I use `tldr -p common find` it works :-(

**Comment by bl-ue** [comment]
Hi, I'll take a look at this tomorrow.

**Comment by MasterOdin** [comment]
Done with #151
