### ISSUE TITLE
Error fetching from tldr: <urlopen error [Errno 104] Connection reset by peer>

### ISSUE THREAD

**Issue by ysl2** [tldr-pages/tldr-python-client#152]
OS: Manjaro KDE

I used `pip install tldr` command to install, after installing, I tried to run `tldr ls` and got this tips:
![image](https://user-images.githubusercontent.com/39717545/104527222-2b0af980-563f-11eb-9778-7bf543ff8881.png)

**Comment by ysl2** [comment]
I uninstalled the pip tldr, and reinstalled tldr-python-client via pacman, then I rebooted my computer and run `tldr` command, but I didn't get any response.

**Comment by bl-ue** [comment]
It just sits there, or immediately exits without printing anything?

**Comment by ysl2** [comment]
![image](https://user-images.githubusercontent.com/39717545/104811850-5d804680-5839-11eb-9fca-37e3fb82438b.png)

**Comment by bl-ue** [comment]
Do you have a proxy?

**Comment by ysl2** [comment]
Maybe I have to set my network... you know, I have to use vpn in my country....
I will try my best to try to solve this. But if I can't do that. I have to come baak. Thank you :-)
