### ISSUE TITLE
Error fetching from tldr: <urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by geosmart** [tldr-pages/tldr-python-client#159]
$ tldr tar                                                                                                                                   [23:55:38]
Error fetching from tldr: <urlopen error [Errno 111] Connection refused>
FAIL: 1

**Comment by yanhanBazoooka** [comment]
Also having the same error message, running on wsl Ubuntu. 
$ tldr tar
Error fetching from tldr: <urlopen error [Errno 111] Connection refused>

**Comment by kbdharun** [comment]
@yanhanBazoooka Can you update the cache with `tldr -u` and try again?

Also, can you provide additional details on how you installed the Python client on WSL? (Snap? Pip?)

**Comment by yanhanBazoooka** [comment]
@kbdharun Thanks for the reply! cache update worked for me. Would you mind explain how is this related to cache update? I used snap to install tldr.

**Comment by kbdharun** [comment]
> @kbdharun Thanks for the reply! cache update worked for me. Would you mind explain how is this related to cache update? I used snap to install tldr.

Sure, this issue was first reported at https://github.com/tldr-pages/tldr-python-client/issues/150, the Python client fetches the page directly from GitHub, which was later updated to use cache first. This issue seems to crop up when there is an issue with the network when it is fetching the page to cache (and it can be fixed by manually updating it).

**Comment by yanhanBazoooka** [comment]
> > @kbdharun Thanks for the reply! cache update worked for me. Would you mind explain how is this related to cache update? I used snap to install tldr.
> 
> Sure, this issue was first reported at #150, the Python client fetches the page directly from GitHub, which was later updated to use the cache first. This issue seems to crop up when there is an issue with the network when it is fetching the cache (and it can be fixed by manually updating it).

Very educational, thanks!
