### ISSUE TITLE
No man page for tldr

### ISSUE THREAD

**Issue by nelaaro** [tldr-pages/tldr-python-client#162]
Expected outcom

   man tldr 

Shows the manage with detailed description of all the options available to this tldr client.

**Comment by CleanMachine1** [comment]
How have you installed tldr?

Could you be more specific in what you mean?

**Comment by marchersimon** [comment]
Unfortutately, we don't have a man-page for this client. You can find every available option with `tldr --help`.

I you'd like to, you can contributa a man page tough, just open a PR for that.

**Comment by dwy6626** [comment]
why not use `tldr tldr` XD

**Comment by marchersimon** [comment]
I'll close this issue now, since there hasn't been any activity lately

**Comment by MasterOdin** [comment]
@marchersimon I'd prefer to leave this issue open. Just because there's not any activity doesn't make this issue less valid of a request or something that would ideally happen.
