### ISSUE TITLE
Coloring for printed { } is broken

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr-python-client#184]
![image](https://user-images.githubusercontent.com/42812113/150630464-a39f5f33-e2d3-4476-a13a-11d274bba991.png)

Sample tldr page:

```yml
# awk

> A versatile programming language for working on files.
> See also: `sed`, `ed`.
> More information: <https://manned.org/awk.1>.

- Execute commands:

`awk '{{{ print gensub("apple", "mango", "g") }}}'`

```

The last `}` displayed must be red too.

**Comment by MasterOdin** [comment]
I'm not sure what exactly you're looking for here. Is it that `{ }` characters shouldn't be removed? That the `}` character is not colored the same as the rest of the example? Happy to help try to address this, but I'm at a loss one what the user expectation is as I don't use `awk` that much so none of these commands much sense to me.

**Comment by EmilySeville7cfg** [comment]
> That the } character is not colored the same as the rest of the example?

Yes.
