### ISSUE TITLE
Parameters in command line are not parsed and not painted

### ISSUE THREAD

**Issue by bwh1te** [tldr-pages/tldr-python-client#19]
What I expect to see (picture from tldr main page)
![tldr-expectations](https://cloud.githubusercontent.com/assets/946520/12147291/f82785fa-b4b9-11e5-9fb3-2c57d484215d.png)

What I actually see
![bwh1te bwh1te-peka _005](https://cloud.githubusercontent.com/assets/946520/12147168/604f729c-b4b9-11e5-857a-f178a20d6567.png)

As we can see on this screenshot, param pattern `{{user_param}}` is not parsing by python client. Since it doesn't parse, it can't be painted like it does on first pic.

What we should do:
1. Add new `DEFAULT_COLORS` entry (`parameter` for example)
2. Parse `command` lines for `{{param}}` patterns and paint in `parameter` color
3. Another parts of the line should be painted in `command` color
4. Except the first two spaces (as we can see on first pic)

**Comment by bwh1te** [comment]
Created pull-request: https://github.com/tldr-pages/tldr-python-client/pull/20

**Comment by felixonmars** [comment]
Merged #20. Thanks again!
