### ISSUE TITLE
Show notice about another similar pages

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [tldr-pages/tldr-python-client#193]
For instance there are two pages with the same name in `common/` and `linux`. Before each page in output we can write smth like:

- `There are another page versions in: common.` (for `linux/`)
- `There are another page versions in: linux.` (for `common/`)

Note that difference between these pages are:

- `common/` uses short options for the most frequently used arguments and long for others
- `linux/` uses long options for all situations

**Comment by CleanMachine1** [comment]
I like this idea.


However I'd word it as `There are other versions of this page in the ___ category.` with ___ being filled with common for example.
