### ISSUE TITLE
Fetch individual translation archives for cache based on the environment variable configuration

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr-python-client#217]
As specified in [Client Specification 2.0](https://github.com/tldr-pages/tldr/blob/v2.0/CLIENT-SPECIFICATION.md)

_If appropriate, it is RECOMMENDED that clients implement a cache of pages. If implemented, clients MUST download the entire archive either as a whole from https://tldr.sh/assets/tldr.zip (Which redirects to https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets/tldr.zip) or download language-specific translation archives in the format https://tldr.sh/assets/tldr-pages.{{language-code}}.zip (Which redirects to [https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets/tldr-pages.{{language-code}}.zip](https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets)), along with the archive for English from https://tldr.sh/assets/tldr-pages.zip (It redirects to https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets/tldr-pages.zip)._

_Caching SHOULD be done according to the user's language configuration (if any), to not waste unneeded space for unused languages. Additionally, clients MAY automatically update the cache regularly._

So, we need to update the client behaviour to work with fetching only the specified language's archive when fetching based on configuration or via the `tldr <page> --language <language-code>` command, we can include English by default as a fallback.

**Comment by SaurabhDRao** [comment]
Hello! Can I take this up ?

Below are the changes that needs to be done right ?
- if a language is set, then fetch only the data for that particular language from the respective language archive location.
- if no language is set, then fetch the english archive as default.

**Comment by kbdharun** [comment]
> Hello! Can I take this up ?

Sure

> Below are the changes that needs to be done right ?
> 
> * if a language is set, then fetch only the data for that particular language from the respective language archive location.
> * if no language is set, then fetch the english archive as default.

Yes, if a language is set only the language and English translation archive must be fetched and when a page isn't translated the client needs to fall back to the English page.

**Comment by SaurabhDRao** [comment]
I have added change for pulling the language specific archives into cache. (#218)

But I noticed that the fallback on en is already present. In the `get_page` function, there is a call to get a list of all languages where it is attaching the default language (en) at the end. Let me know if I am missing something.
