### ISSUE TITLE
traceback error on Debian

### ISSUE THREAD

**Issue by mansoorbarri** [tldr-pages/tldr-python-client#219]
i'm getting the following error: 
```bash 
Traceback (most recent call last):
  File "/usr/local/bin/tldr", line 5, in <module>
    from tldr import cli
ModuleNotFoundError: No module named 'tldr'
``` 

Machine: 
Debian 12
Kernal: 6.1.0-12
DE: GNOME 43.6

**Comment by kbdharun** [comment]
Hi, we don't have our official client's packages in Debian. If you installed it through `pip` then I would suggest trying to reinstall it.

Alternatively, if you use Snap. You can install the Python client through it with the command `snap install tldr`.

**Comment by mansoorbarri** [comment]
both failed, I did it via npm which works. The formatting isn't there though but its fine
