### ISSUE TITLE
`tldr --search "KEYWORDS"` does not work

### ISSUE THREAD

**Issue by fazlearefin** [tldr-pages/tldr-python-client#231]
`tldr --search` seems to be not implemented

```console
❯ tldr --version
tldr 3.2.0 (Client Specification 1.5)
❯ tldr --search memory
Please update cache
❯ tldr --search ls
Please update cache
❯
```

**Comment by owenvoke** [comment]
For some reason it's `--update_cache` (or `-u`). 🤔

**Comment by fazlearefin** [comment]
> `tldr --search` seems to be not implemented
> 
> ```
> ❯ tldr --version
> tldr 3.2.0 (Client Specification 1.5)
> ❯ tldr --search memory
> Please update cache
> ❯ tldr --search ls
> Please update cache
> ❯
> ```

**Comment by fazlearefin** [comment]
> For some reason it's `--update_cache` (or `-u`). 🤔
> 
> https://github.com/tldr-pages/tldr-python-client/blob/6536569d4ab954dec33aa9166df940a918094c83/tldr.py#L431
> 
> I think we should alias this if possible, so it's `--update` (but support `--update_cache` for backwards compatibility).

Sorry for the confusion. I meant to say `tldr --search` does not work

**Comment by kbdharun** [comment]
Can confirm this issue, I was able to replicate it too.

**Comment by owenvoke** [comment]
Ah, my bad. 👍🏻 Well, I opened a PR to add the `--update` support anyway. 🤷🏻 https://github.com/tldr-pages/tldr-python-client/pull/232
