### ISSUE TITLE
BSDs are supported, but cannot be passed to the `--platform` option 

### ISSUE THREAD

**Issue by acuteenvy** [tldr-pages/tldr-python-client#235]
The client supports displaying BSD pages without specifying `--platform` (e.g. `tldr pkgin`), but displays an error when the option is used (e.g. `tldr --platform netbsd pkgin`):
```
$ tldr pkgin
no errors, the page is rendered as it should

$ tldr --platform netbsd pkgin
usage: tldr command [options]
tldr: error: argument -p/--platform: invalid choice: 'netbsd' (choose from 'linux', 'osx', 'sunos', 'windows', 'common')
```

**Comment by owenvoke** [comment]
This was probably implemented before `netbsd` was added to tldr pages. 🤔 I think it should be fine to add `netbsd` as an option. 👍🏻

I've created support for this here: https://github.com/tldr-pages/tldr-python-client/pull/236
