### ISSUE TITLE
Plans for new release?

### ISSUE THREAD

**Issue by frenzymadness** [tldr-pages/tldr-python-client#237]
Hello. It has been 10 months since the latest release 3.2.0. Do you plan to do a new release? There are some useful fixes in the main branch.

**Comment by kbdharun** [comment]
Yes, we plan on making a new release soon,  waiting for the major client specification release to come through https://github.com/tldr-pages/tldr/milestone/3 after which we need to update the caching URLs and implement placeholder escaping to comply with it fully.
