### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by bwh1te** [tldr-pages/tldr-python-client#24]
Subj. It would be clearly to see list of changes according to version numbers. It may be simply a digest of commit messages for each version.

**Comment by waldyrious** [comment]
This could be a job for [github-changelog-generator](https://github.com/skywinder/github-changelog-generator) (or one of [its alternatives](https://github.com/skywinder/Github-Changelog-Generator/wiki/Alternatives)).

**Comment by zdroid** [comment]
Does this client actually have versions?
@waldyrious Are you still interested in implementing this? Perhaps this should be utilized in the whole project.

**Comment by waldyrious** [comment]
I don't have the bandwidth to work on this myself, unfortunately, but I still think it would be a good idea to use an automated tool to automatically collect release information. Not sure what you mean by "the whole project", btw.

**Comment by zdroid** [comment]
@waldyrious for all repos in tldr-pages organization, that's what I meant.

**Comment by waldyrious** [comment]
Not sure it's worth it for all repos. It only makes sense for those that make releases regularly, like this one or the node client.
