### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by jtele2** [tldr-pages/tldr-python-client#240]
## Issue

I'm getting a _Error: certificate has expired_ when trying to use `tldr`. 

## Environment

I'm running Ubuntu 22.04 on _Ubuntu multicloud_ on my 2014 mbp. `tldr` version is 3.3.2. I installed `tldr` with `pipx`.

```
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

## Error Logs

```
tldr tar
⠇ Page not found. Updating cache...{ Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'CERT_HAS_EXPIRED' }
```

**Comment by CleanMachine1** [comment]
Hi, did you ever resolve this.
By the looks of things its likely a problem with cert management on your computer (eg time or outdated package)

**Comment by kbdharun** [comment]
Hi, as CleanMachine1 says above, it is probably an issue with the local certificate management in your Ubuntu environment, not with the client. So I am closing this issue. Feel free to try out installing our client using Snap (it is isolated from the host) and will probably work fine (`snap install tldr`), if the issue persists please review the certificates in your environment.
