### ISSUE TITLE
Stylize text inside `backticks` when appearing in example description

### ISSUE THREAD

**Issue by fazlearefin** [tldr-pages/tldr-python-client#253]
The python client does not stylize text inside tilde when it appears in the example description (please see screenshot). The rust client **tlrc** does stylize text when it appears inside ``

The python client needs to stylize text inside `` when it appears in the description.

![Screenshot from 2024-09-06 20-45-25](https://github.com/user-attachments/assets/4a34047c-6680-4718-8e15-b5454598c29f)

**Comment by fazlearefin** [comment]
The rust client does stylize text inside `` even when it appears in the description of examples:

![Screenshot from 2024-09-07 16-47-24](https://github.com/user-attachments/assets/61709e81-1462-4347-9d2c-e2bb2e6eedbe)

**Comment by kyluca** [comment]
Hi, hoping to contribute to this issue as part of Hacktoberfest :)

I've just put up #254, please let me know if it's suitable or if there's anything else I can do.

Cheers,
Kyle
