### ISSUE TITLE
support offline pages

### ISSUE THREAD

**Issue by 1-61803** [tldr-pages/tldr-python-client#40]
As of now, all `tldr` pages are ~370KB. Instead of being saved all at once, they are cached for each command when the client runs and it doesn't use the same folder structure as `tldr` (common, linux, etc), but adds a suffix for each one (e.g. `awk_common.md`).

**Comment by TimothyBramlett** [comment]
@1-61803 Can you change the tldr url for the C++ clients, do you know?

**Comment by zdroid** [comment]
Solved in #88, try it out. :smile:
