### ISSUE TITLE
ValueError: need more than 0 values to unpack while running manage.status

### ISSUE THREAD

**Issue by bocu** [tldr-pages/tldr-python-client#46]
Hello,

I have a salt-master. I also have a minion, running not on the same machine with the master, but instead, it is a separate box sitting on the same network. I have not accepted the key of that minion on salt-master side. Here are the keys on the master side:

```
salt-key -l all
Accepted Keys:
Denied Keys:
Unaccepted Keys:
BL1706002
Rejected Keys:
```

Minion-id of my minion is BL1706002.

When I run the manage.status command on the master side I get the following error:

```
salt-run manage.status
No minions matched the target. No command was sent, no jid was assigned.
Exception occurred in runner manage.status: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/manage.py", line 73, in status
    ret['up'], ret['down'] = _ping(tgt, expr_form, __opts__['timeout'])
ValueError: need more than 0 values to unpack
```
This used to work. But I recently started getting this error and this error is breaking the UI of the application that I am developing. I can make my code to catch this error, digest it and gracefully continue as if there were no problems, but it didn't sound a correct solution to go with to me. So, instead, I wanted to ask you guys, what your opinions are.

Is this the normal behavior? Am I missing something ? What do you guys suggest?

Thank you very much

PS: Extra information

```
salt-master --version
salt-master 2016.11.2 (Carbon)
```

```
uname -a
Linux xxxxxxxxxxxx 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
```

**Comment by bocu** [comment]
Oppps.. My bad guys, I posted it to wrong project. I am so sorry.

**Comment by waldyrious** [comment]
No problem @bocu. I'll close the issue, then.
