### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr-python-client#47]
The [current version on PyPI](https://pypi.python.org/pypi/tldr), v0.3, has a bunch of bugs that have been fixed in the master version, such as #31 and #32.

I can make a [new release on github](https://github.com/tldr-pages/tldr-python-client/releases), but I can't update the PyPI package, as only @felixonmars has access. So this issue is two-fold:

1) make a new release here and on PyPI

2) add some people as owners/maintainers in PyPI ([example](https://pypi.python.org/pypi/mwclient#downloads))

**Comment by waldyrious** [comment]
Does anyone know of a way to get access to a PyPI package if the original author is unreachable? Lots of people are being affected by issues that are already solved in the unreleased version.

**Comment by waldyrious** [comment]
Re-pinging @felixonmars in the meantime. Please just add another maintainer to the PyPI package if you can -- hopefully that won't take up much of your time.

**Comment by felixonmars** [comment]
Sorry, somehow I forgot this for multiple times. Which PyPI username should I add?

**Comment by waldyrious** [comment]
Please add me (waldyrious). I'm not a Python developer, but I tend to be reasonably active on github and will make sure to give access (if the permissions on PyPI allow me) to other contributors to this package who wish to help with the release process. This way, hopefully the releases will be less prone to bottlenecks. Sounds good to you?

(it probably makes sense to give access to @rprieto as well, and the currently active maintainers of the tldr-pages project, @agnivade and @sbrl)

**Comment by felixonmars** [comment]
OK, waldyrious added as owner of pypi:tldr. The other three usernames are not present on PyPI.

**Comment by waldyrious** [comment]
Thanks. Are you planning to make the new release yourself, or should I?

**Comment by felixonmars** [comment]
Just made a new release, please let me know if there is any problem :)

**Comment by JacobCallahan** [comment]
The upgrade completed perfectly! https://i.imgur.com/nl0cIC5.png

**Comment by agnivade** [comment]
Do I need to register or is this taken care of ?

**Comment by waldyrious** [comment]
@agnivade it would be nice to have various alternative routes to avoid bottlenecks in the future. I'd suggest you to register just in case :)

**Comment by agnivade** [comment]
Done. Username - agniva

**Comment by felixonmars** [comment]
agniva added as owner of tldr on PyPI.
