### ISSUE TITLE
What the 'tldr' means?

### ISSUE THREAD

**Issue by OrangePJ** [tldr-pages/tldr-python-client#51]

**Comment by JacobCallahan** [comment]
Can you elaborate on this issue? Are you just asking what "tldr" means? Or are you asking for some kind of additional in-product documentation for this? If the first, "tldr" means "too long, didn't read".

**Comment by waldyrious** [comment]
I'm assuming this issue is asking about the meaning of the tldr acronym. @JacobCallahan already explained it above, and besides it's described in the main tldr-pages repository: https://github.com/tldr-pages/tldr#what-does-tldr-mean.

Feel free to clarify in case you meant something else.

**Comment by OrangePJ** [comment]
@JacobCallahan @waldyrious 
I knew it, "too long, didn't read".
Good name
