### ISSUE TITLE
tldr package in Fedora

### ISSUE THREAD

**Issue by frenzymadness** [tldr-pages/tldr-python-client#52]
Hello.

tldr will be available as a package for Fedora Linux soon. Could I add it as an option for installation? Just asking before creating PR.

Thanks and have a nice day.

**Comment by waldyrious** [comment]
Yes, a PR would be most welcome :) please go ahead at your leisure.

**Comment by JacobCallahan** [comment]
@frenzymadness any update on this?

**Comment by frenzymadness** [comment]
I totally forget about it, sorry. Pull request is ready now.
