### ISSUE TITLE
Respect default terminal colours

### ISSUE THREAD

**Issue by torsava** [tldr-pages/tldr-python-client#53]
Hi! I'm a big believer in sane defaults, and the default colour scheme of tldr seems to me anything but.

Would it be possible to use the default background/text/hightlight/... colors from the terminal instead of forcing users to configure it?

**Comment by JacobCallahan** [comment]
@torsava what version of the client are you running?

**Comment by torsava** [comment]
I just pip-installed it, it's 0.4.1.

**Comment by JacobCallahan** [comment]
@torsava can you provide a screenshot? The upgrade to 0.4.1 solved the bad color scheme I was seeing on my system https://github.com/tldr-pages/tldr-python-client/issues/47#issuecomment-347893698

**Comment by torsava** [comment]
![2017-12-07-153258_1344x756_scrot](https://user-images.githubusercontent.com/17247852/33720380-162454a2-db64-11e7-83c5-645b8b8f9ca9.png)

I'm using ZSH instead of bash and it's inside a tmux session.

**Comment by JacobCallahan** [comment]
@torsava interesting. I've verified that colors remain consistent within tmux, and zsh on my end as well. The default colors don't set a background color either [1]. Not sure what is going on for you..
![screenshot](https://i.imgur.com/ZuPqi2b.png)

[1] - https://github.com/tldr-pages/tldr-python-client/blob/master/tldr.py#L175

**Comment by waldyrious** [comment]
Perhaps remnant configuration from a previous install?

**Comment by torsava** [comment]
@waldyrious You mean a configuration in .bashrc? No, there's none, just checked. I'm not even sure I installed this before now.

**Comment by waldyrious** [comment]
I meant configuration specific to the python tldr client, perhaps in a dedicated file. I'm not sure where it could be stored (I don't use this client myself), but it seemed to be a plausible explanation. If you're not sure you had installed this before, please re-check so we can rule out (or confirm) that hypothesis.

**Comment by torsava** [comment]
So, you were right. I found that there's a `~/.tldr_cache` directory and after deleting it, terminal colours are respected! It might be a good idea to mention this directory in the README.

Thanks for your help!

**Comment by waldyrious** [comment]
Glad the mystery was solved :)

As for mentioning this on the README: I initially thought it wasn't warranted since that directory is not used anymore (see #37 and #43); but perhaps others will have the same issues as you, so a PR adding this note to the README would be most welcome.

**Comment by torsava** [comment]
Alright, I'll send a PR next week!

**Comment by HalisCz** [comment]
I would like to reopen this issue.

I am using (KDE Plasma 5) Konsole with included colorscheme "Solarized Light", and basic font is almost invisible (as you can see below).

![obrazek](https://user-images.githubusercontent.com/1120890/34206620-94a8ddac-e587-11e7-9a4f-270125ee32f2.png)

I know that "background" color and "color8" are almost the same, but I think that Solarized is so popular, that this should be handled somehow.

What do you think?

**Comment by felixonmars** [comment]
Will any of the environment variables listed in README https://github.com/tldr-pages/tldr-python-client#configuration help on your configuration?

**Comment by HalisCz** [comment]
@felixonmars actually no, because there is some strange behaviour:

Steps:

1. I've tried `tldr vim`. Output is OK, font is hard to read due to it's color.
2. `export TLDR_COLOR_DESCRIPTION="black"`
3. I've tried `tldr vim`. Output is `No internet connection detected. Please reconnect and try again.`
4. `unset TLDR_COLOR_DESCRIPTION`
5. I've tried `tldr vim`. Output is OK, font is hard to read due to it's color

**Comment by JacobCallahan** [comment]
@HalisCz it looks like you're trying to set the variable to an invalid color choice. See this section for acceptable choices.
https://github.com/tldr-pages/tldr-python-client#colors

**Comment by HalisCz** [comment]
@JacobCallahan you were right. I tried the same with `blue` and it worked.

But I am still confused ... why there are not used system default colors in the first place as sane defaults?
