### ISSUE TITLE
Add new collaborators to the repo

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr-python-client#55]
Following https://github.com/tldr-pages/tldr/issues/1878, I'm inviting all contributors to this repo that meet the criteria specified in https://github.com/tldr-pages/tldr/issues/1839 for being added as collaborators. They are:
- [ ] @igorshubovych ([contributions](https://github.com/tldr-pages/tldr-python-client/commits?author=igorshubovych))
- [x] @Anmol-Singh-Jaggi ([contributions](https://github.com/tldr-pages/tldr-python-client/commits?author=Anmol-Singh-Jaggi))
- [x] @PacoHobi ([contributions](https://github.com/tldr-pages/tldr-python-client/commits?author=PacoHobi))
- [ ] @mdshw5 ([contributions](https://github.com/tldr-pages/tldr-python-client/commits?author=mdshw5))

Welcome aboard!

Note: all contributors above were invited with write permissions. @felixonmars, as the creator and main author of this repo, retains admin permissions.

This issue will remain open until the invitations are either accepted or declined.

**Comment by zdroid** [comment]
@waldyrious Shouldn't this be closed now?

**Comment by waldyrious** [comment]
Have they accepted the invitation? I can't check right now, I'm on my phone.

**Comment by zdroid** [comment]
I can't view either, as I am not org owner. But what I meant is, 2 years is a fairly reasonable time period for someone to accept / decline an invitation. :laughing:
