### ISSUE TITLE
No internet connection detected. Please reconnect and try again.

### ISSUE THREAD

**Issue by Eva-Sanya** [tldr-pages/tldr-python-client#57]
Keep getting this error on OSX high sierra on command prompt. The session has internet connectivity and i'm able to get to it.

Any help will be appreciated. Thanks.

-m

**Comment by JacobCallahan** [comment]
This is likely a duplicate of #56. If you agree, please close this and add your comment there.

**Comment by TimothyBramlett** [comment]
Same problem.  Will look at #56

**Comment by zdroid** [comment]
Closing this as it's identical to #56.
