### ISSUE TITLE
Autocompletion for shells

### ISSUE THREAD

**Issue by founderio** [tldr-pages/tldr-python-client#69]
Auto completion for the cli options and available pages would be nice.
Something along the lines of the zsh and bash completions here: https://github.com/tldr-pages/tldr-node-client/tree/master/bin

This client currently does not have an option to list all available pages it seems, which would be a requirement.

**Comment by jn64** [comment]
Here is a quick solution for bash autocomplete. Simply add to `.bashrc` or other file that is sourced in your shell:

```shell
TLDR_CACHE_DIR="${HOME}/.cache/tldr"
complete -W "$(q=(${TLDR_CACHE_DIR}/*); sed 's/\_[a-zA-Z]\+\.md/ /g' <<<${q[@]##*/})" tldr
```

Based on [tldr-bash-client](https://gitlab.com/pepa65/tldr-bash-client#autocompletion)

(I'm using tldr-python-client v0.5 as packaged on Fedora 32, have not updated to 1.0)

**Comment by zdroid** [comment]
@jn64 This probably can be implemented nicely in Python too.

**Comment by merwok** [comment]
For reference, I think this is the classic tool used for this: https://pypi.org/project/argcomplete/

**Comment by MasterOdin** [comment]
I think using argcomplete is probably the better move as it would allow us to handle autocompletion for a specific language / platform, be it specified by configuration or option flag. Adding this to 1.1 milestone.

**Comment by zdroid** [comment]
@merwok Good idea, thanks for noting.
