### ISSUE TITLE
Don't change the background color of the shell

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr-python-client#7]
Currently it's changing the background color to blue (like in the screenshot in https://github.com/tldr-pages/tldr); that's unnecessary and the result isn't exactly pretty.

**Comment by Konfekt** [comment]
Hm, the output is completely unreadable with the current background color. Is it not possible to change this under Python?

**Comment by Konfekt** [comment]
Ok, someone gotta implement the suggestion at https://github.com/tldr-pages/tldr/issues/256#issuecomment-68698482 of a .tldr file that disables coloring for good.

**Comment by rprieto** [comment]
For now I think only the `Node` client implements a `.tldr` config. If other clients do it too (which would be great) maybe we should standardise the format?

I'll start a `implementing a client` guide in the main TLDR repo.

**Comment by drobati** [comment]
Yeah, I hate that the background changed too.

**Comment by waldyrious** [comment]
With #25 now merged, fixing this is only a matter of making that the default (which I support).

**Comment by felixonmars** [comment]
I don't like the background color myself either, but I would want to keep it the same with the node.js client.

**Comment by igorshubovych** [comment]
@felixonmars 
I would not count on Node client.

We have [color themes](https://github.com/tldr-pages/tldr-node-client/pull/61) coming.

It's a breaking change, so it might be merged in some time. But it will happen. So you'd rather do whatever is the best for users.

**Comment by waldyrious** [comment]
Can anyone confirm if the latest master (after merging #32) fixes this issue? I am not particularly versed on Python development. I tried `pip install git+https://github.com/tldr-pages/tldr-python-client.git` but `tldr tar` only prints three empty lines...

**Comment by lots0logs** [comment]
@waldyrious I'm not sure why it only prints empty lines for `tar` but if you try other commands it works fine, like for example `tldr wget`.

**Comment by waldyrious** [comment]
Whoa. Indeed, I can reproduce that. The plot thickens... 😕 I'll open an issue to track that. In the meantime, the color change seems to have worked, so I'll close #7.

**Comment by waldyrious** [comment]
For future reference, the `tar` issue was #31, which was fixed in #36.

**Comment by waldyrious** [comment]
In light of #49, I'll reopen this issue to avoid misleading people about features that aren't yet available in the released version.

**Comment by felixonmars** [comment]
Fixed in 0.4.1.
