### ISSUE TITLE
command execute too slow

### ISSUE THREAD

**Issue by Maslino** [tldr-pages/tldr-python-client#8]
to fetch corresponding page from remote repository every time is very slow.

**Comment by Anmol-Singh-Jaggi** [comment]
So, what solution do you suggest?

**Comment by bwh1te** [comment]
It is not client issue. Client only downloads data from source. Low speed of execution is only dues to network interaction. Maybe owner should close this issue?

**Comment by Maslino** [comment]
a page cache may be needed

**Comment by bwh1te** [comment]
Yep, I think too. Related issue: https://github.com/tldr-pages/tldr-python-client/issues/15

**Comment by Anmol-Singh-Jaggi** [comment]
If only if this project was written using Python3, we could have used the [in-built cache decorator](https://docs.python.org/dev/library/functools.html#functools.lru_cache) which would have allowed us to implement caching just by adding one line to the source code.

**Comment by bwh1te** [comment]
`tldr` is not working permanently like a daemon. In other words, anytime you execute `tldr command_name`, you have a new instance of application with empty LRU cache. So it won't help. 

I think we need to create some dir like `~/.tldr/cache` during installation and store server answers there. And doing requests with `If-Modified` header. But answer size is not so big... More time will to take  connection to server, than get small text response... We may not to request server each time, but how we can know that our cache is up to date?

So cache is important but I guess not to accelerate each command. Just for case when server is not available.

**Comment by Anmol-Singh-Jaggi** [comment]
Good idea! I'll implement it when I get the time.

**Comment by felixonmars** [comment]
Implemented in newer versions.

**Comment by zessu** [comment]
Try updating TLDR to latest version **npm install -g tldr**
If this does not work, try running bunx tldr [package] e.g **bunx tldr tmux** or if you are using npm, **npx tldr tmux**
