### ISSUE TITLE
Private pages in tldr

### ISSUE THREAD

**Issue by debek** [tldr-pages/tldr-python-client#87]
Hi!

Is it possible to run private pages? I cannot find this option.

**Comment by zdroid** [comment]
What do you mean by running private pages? Maybe you want to use tldr interface to access some pages made by you? If that's the case, tldr doesn't provide the interface for that, at least not right now.

This seems like an issue for https://github.com/tldr-pages/tldr/issues, and not this repository.

**Comment by waldyrious** [comment]
> This seems like an issue for tldr-pages/tldr/issues, and not this repository.

@zdroid I believe that is a feature that individual clients can choose to implement, e.g. https://github.com/isacikgoz/tldr/issues/4

So it would make sense to keep this issue here and not in the pages repository.

**Comment by zdroid** [comment]
@waldyrious Thanks for pointing that out, I haven't seen it before. Was there a discussion about it in tldr-pages/tldr?

**Comment by waldyrious** [comment]
I believe so, but on a brief search I couldn't find previous discussions. If anyone remembers where this was mentioned, please add the links here.
