### ISSUE TITLE
Drop python2 support

### ISSUE THREAD

**Issue by MasterOdin** [tldr-pages/tldr-python-client#93]
Given that Python2 was deprecated on January 1st, 2020, and its last version was released a few days ago, I would like to propose removing support in this client for python2, and only focus on python3. Python2 is also being phased out increasingly from various Linux distros to be harder and harder to install. Principally, this would just involve:

* changing the shebang to be `#!/usr/bin/env python3` instead of `#!/usr/bin/env python`
* remove usage of `__future__`
* remove `six` as dependency

**Comment by zdroid** [comment]
Ubuntu still supports it, so that might be a problem at this phase. But at some point in the future, why not.

**Comment by MasterOdin** [comment]
Why? The current oldest supported LTS (excluding the extended support they offer for money) is 16.04 which has Python 3.5 out of the box. By the logic of "Ubuntu supports it", that would mean you would remove python2 support at the earliest in 2025 (when 20.04 exits LTS)?

**Comment by zdroid** [comment]
You're right, it seems I forgot that python3 was installed by default even in way older versions. Your argument makes complete sense now.
@felixonmars any opinions on this? I'm for the change.

**Comment by zdroid** [comment]
@waldyrious @felixonmars any opinions on this? I'm for the change.

**Comment by felixonmars** [comment]
I'd like to drop support for Python 2 too. PRs welcome!

**Comment by waldyrious** [comment]
With the EOL of Python2, and Python3 widely available in most systems, I don't see any serious downsides in migrating either :)
